### ISSUE TITLE
[FEATURE] Create Documentation

### ISSUE THREAD

**Issue by DonaldLouch** [DevLexicon/OpusVid#6]
### Feature Description
Create the Documentation.

### Include
- [ ] Google Captcha Link and Keys
- [ ] DigitalOcean Spcaes Link and Keys
- [ ] How To Upload SQL
- [ ] Initial Settings

### From "Issues"
- [ ] Add: #1 (Spaces Issue) to documentation
- [ ] Add: #11 (Video Upload) to documentation
- [ ] Add: #8 (Terms of Service Page) to documentation
- [ ] Add: #14 (Settings) to documentation
- [ ] Add #15 (CSS Settings) to documentation
- [ ] Add #19 (Error Messages) description and examples to the documentation
- [ ] Add #4 "[BUG] Share Button is missing" Solution to the documentation 

### Versions
- [ ] LIMITED: Community Version
- [ ] FULL: License Version

**Comment by DevLexicon** [comment]
Add: #1 (Spaces Issue) to documentation.

**Comment by DevLexicon** [comment]
Add: #11 (Video Upload) to documentation.

**Comment by DevLexicon** [comment]
Add: #8 (Terms of Service Page) to documentation.
- [ ] Added

**Comment by DevLexicon** [comment]
Add: #14 (Settings) to documentation
- [ ] Added

**Comment by DevLexicon** [comment]
Add #15 (CSS Settings) to documentation
- [ ] Added

**Comment by DevLexicon** [comment]
Add #19 (Error Messages) description and examples to the documentation.
- [ ] Added
